CREATE DATABASE opel_api DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE project (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  description VARCHAR(64) NOT NULL,
  name VARCHAR NOT NULL DEFAULT 0,
  created DATETIME NOT NULL DEFAULT NOW(),
  last_updated DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW()
);
